# Generated by Django 5.2.8 on 2026-02-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=11)),
                ('token', models.CharField(max_length=100, null=True, unique=True)),
                ('code', models.SmallIntegerField()),
            ],
        ),
    ]
