# Generated by Django 5.2.8 on 2025-12-03 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0002_messagemanager_message_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageManager',
        ),
    ]
