# Generated by Django 5.2.8 on 2025-12-03 20:05

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0003_delete_messagemanager'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='message',
            managers=[
                ('unread', django.db.models.manager.Manager()),
            ],
        ),
    ]
