# Generated by Django 5.2.8 on 2025-12-03 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0004_alter_message_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='message',
            managers=[
            ],
        ),
    ]
